config/routes.rb
Rails.application.routes.draw do

  resources :invites

  get 'dashboard' => 'login#index'
  get 'dashboard/user' => 'login#user'
  get 'dashboard/admin' => 'login#admin'
  get 'dashboard/show' => 'login#show'
  get 'dashboard/edit' => 'login#edit'
  delete 'dashboard/delete' => 'login#destroy'
  put 'dashboard/update' => 'login#update'
  get 'login' => 'login#show'

  resources :usertypes
  devise_for :logins, controllers: { registrations: "logins/registrations" }

  

  
  
  root :to => redirect("/logins/sign_in")
  

end

app/models/invite.rb
class Invite < ActiveRecord::Base
	validates_presence_of :email
	# validates_presence_of :company_name
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]

  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.all
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end

  # GET /invites/new
  def new
    @invite = Invite.new
    @login = Login.all.where(company_name: current_login.company_name).first
  end

  # GET /invites/1/edit
  def edit
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(invite_params)
    # @login = Login.all.where(company_name: current_login.company_name).first
    # @login.save
  

    respond_to do |format|
      if @invite.save

        #Email Configuration
          Mymail.jkmail(@invite).deliver

        format.html { redirect_to dashboard_path, notice: 'Invitation sent successfully.' }
        format.json { render :show, status: :created, location: @invite }
      else
        format.html { render :new }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { render :edit }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to invites_url, notice: 'Invite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:email, :company_name)
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <!-- <div id="error_explanation"> -->
    <div  class="form-group alert alert-danger alert-dismissable">
      <button type="button" class="close" aria-hidden="true">&times;</button>
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<form class="form-inline" role="form">
   
   <%= f.hidden_field :company_name,  :value => @login.company_name,  class: "form-control" %>
   
    <div class="input-group center">
      <!-- <%= f.label :email %> -->
      <%= f.email_field :email, :required => true, class: "form-control" %>

      <span class="input-group-btn">
        <%= f.submit "Invite", class: "btn btn-success" %>
      </span>
    </div>
</form>
<% end %>

app/views/invites/edit.html.erb
<h1>Editing invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<h1>Listing invites</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Company Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invites.each do |invite| %>
      <tr>
        <td><%= invite.email %></td>
        <td><%= invite.company_name %></td>
        <td><%= link_to 'Show', invite %></td>
        <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
        <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invite', new_invite_path %>

app/views/invites/new.html.erb
<div class="panel panel-primary span-5">
  <div class="panel-heading"><h4>Invite Team Members to Mingle.camp!</h4></div>
  	<div class="panel-body">
 		<%= render 'form' %>
  	</div>
</div>

<!-- <%= link_to 'Back', invites_path %> -->

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @invite.email %>
</p>
<p>
  <strong>Company Name:</strong>
  <%= @invite.company_name %>
</p>

<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>