config/routes.rb
Rails.application.routes.draw do

  resources :invites

  get 'dashboard' => 'login#index'
  get 'dashboard/user' => 'login#user'
  get 'dashboard/admin' => 'login#admin'
  get 'dashboard/show' => 'login#show'
  get 'dashboard/edit' => 'login#edit'
  delete 'dashboard/delete' => 'login#destroy'
  put 'dashboard/update' => 'login#update'
  get 'login' => 'login#show'

  resources :usertypes
  devise_for :logins, controllers: { registrations: "logins/registrations" }

  

  
  
  root :to => redirect("/logins/sign_in")
  

end

app/controllers/usertypes_controller.rb
class UsertypesController < ApplicationController
  before_action :set_usertype, only: [:show, :edit, :update, :destroy]

  # GET /usertypes
  # GET /usertypes.json
  def index
    @usertypes = Usertype.all
  end

  # GET /usertypes/1
  # GET /usertypes/1.json
  def show
  end

  # GET /usertypes/new
  def new
    @usertype = Usertype.new
  end

  # GET /usertypes/1/edit
  def edit
  end

  # POST /usertypes
  # POST /usertypes.json
  def create
    @usertype = Usertype.new(usertype_params)

    respond_to do |format|
      if @usertype.save
        format.html { redirect_to @usertype, notice: 'Usertype was successfully created.' }
        format.json { render :show, status: :created, location: @usertype }
      else
        format.html { render :new }
        format.json { render json: @usertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usertypes/1
  # PATCH/PUT /usertypes/1.json
  def update
    respond_to do |format|
      if @usertype.update(usertype_params)
        format.html { redirect_to @usertype, notice: 'Usertype was successfully updated.' }
        format.json { render :show, status: :ok, location: @usertype }
      else
        format.html { render :edit }
        format.json { render json: @usertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usertypes/1
  # DELETE /usertypes/1.json
  def destroy
    @usertype.destroy
    respond_to do |format|
      format.html { redirect_to usertypes_url, notice: 'Usertype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usertype
      @usertype = Usertype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usertype_params
      params.require(:usertype).permit(:usertype_id, :usertype_name, :can_create, :can_delete, :can_view)
    end
end

app/helpers/usertypes_helper.rb
module UsertypesHelper
end

app/views/usertypes/_form.html.erb
<%= form_for(@usertype) do |f| %>
  <% if @usertype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usertype.errors.count, "error") %> prohibited this usertype from being saved:</h2>

      <ul>
      <% @usertype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usertype_id %><br>
    <%= f.number_field :usertype_id %>
  </div>
  <div class="field">
    <%= f.label :usertype_title %><br>
    <%= f.text_field :usertype_title %>
  </div>
  <div class="field">
    <%= f.label :can_add_user %><br>
    <%= f.text_field :can_add_user %>
  </div>
  <div class="field">
    <%= f.label :can_view_user %><br>
    <%= f.text_field :can_view_user %>
  </div>
  <div class="field">
    <%= f.label :can_delete_user %><br>
    <%= f.text_field :can_delete_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usertypes/edit.html.erb
<h1>Editing usertype</h1>

<%= render 'form' %>

<%= link_to 'Show', @usertype %> |
<%= link_to 'Back', usertypes_path %>

app/views/usertypes/index.html.erb
<h1>Listing usertypes</h1>

<table>
  <thead>
    <tr>
      <th>Usertype</th>
      <th>Usertype name</th>
      <th>Can create</th>
      <th>Can delete</th>
      <th>Can view</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usertypes.each do |usertype| %>
      <tr>
        <td><%= usertype.usertype_id %></td>
        <td><%= usertype.usertype_title %></td>
        <td><%= usertype.can_add_user %></td>
        <td><%= usertype.can_delete_user %></td>
        <td><%= usertype.can_view_user %></td>
        <td><%= link_to 'Show', usertype %></td>
        <td><%= link_to 'Edit', edit_usertype_path(usertype) %></td>
        <td><%= link_to 'Destroy', usertype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usertype', new_usertype_path %>

app/views/usertypes/new.html.erb
<h1>New usertype</h1>

<%= render 'form' %>

<%= link_to 'Back', usertypes_path %>

app/views/usertypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usertype:</strong>
  <%= @usertype.usertype_id %>
</p>

<p>
  <strong>Usertype name:</strong>
  <%= @usertype.usertype_title %>
</p>

<p>
  <strong>Can create:</strong>
  <%= @usertype.can_add_user %>
</p>

<p>
  <strong>Can View:</strong>
  <%= @usertype.can_view_user %>
</p>

<p>
  <strong>Can delete:</strong>
  <%= @usertype.can_delete_user %>
</p>


<%= link_to 'Edit', edit_usertype_path(@usertype) %> |
<%= link_to 'Back', usertypes_path %>