config/routes.rb
Rails.application.routes.draw do

  resources :invites

  get 'dashboard' => 'login#index'
  get 'dashboard/user' => 'login#user'
  get 'dashboard/admin' => 'login#admin'
  get 'dashboard/show' => 'login#show'
  get 'dashboard/edit' => 'login#edit'
  delete 'dashboard/delete' => 'login#destroy'
  put 'dashboard/update' => 'login#update'
  get 'login' => 'login#show'

  resources :usertypes
  devise_for :logins, controllers: { registrations: "logins/registrations" }

  

  
  
  root :to => redirect("/logins/sign_in")
  

end

app/models/login.rb
class Login < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :company, dependent: :destroy
   has_many :usertypes, dependent: :destroy
   belongs_to :logins
end

app/controllers/login_controller.rb
#Customise controller, that handles additional activites of DEVISE GEM
class LoginController < ApplicationController
	 before_filter :authenticate_login!

#dashboard for superAdmin


  def index
  	# @company_names = current_login.company_name
  	@usertype = Usertype.find(1)
    @usertype2 = Usertype.find(2) 
    @login = Login.all.where(company_name: current_login.company_name)

  	@usertype = @usertype.usertype_id
    @usertype2 = @usertype2.usertype_id
  	@curr_usertype = current_login.usertype_id

  
  end

  def new
    @login = Login.new
  end

    # GET /logins/1
  # GET /logins/1.json
  def show
    @login = Login.where(id:params[:id])
  end

    # GET /invites/1/edit
  def edit
     @login = Login.where(id:params[:id]).first
  end

  # PATCH/PUT /Login/1
  # PATCH/PUT /Login/1.json
  def update
    @book = Login.find(params[:id])


    @book.usertype_id =  params[:login][:usertype_id]
    @book.save
    # sad
    # sdfsdfs
    # true
    respond_to do |format|
      if @book
        format.html { redirect_to dashboard_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: dashboard_path }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource
  def destroy
    @login_new = Login.find(params[:id])
    @login_new.delete

    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
   
  end
  

end

app/controllers/logins/registrations_controller.rb
class Logins::RegistrationsController < Devise::RegistrationsController
	# GET /resource/sign_up
  def new()

  	if params[:company_name]
      @company =  Invite.where(company_name: params[:company_name]).first
    end
    
    if params[:email]
      @invite_email =  params[:email]
    end
    

   
      # @login = Login.find(params[:id])
    
    @usertype =  "3" # The usertype will be  USER
  	
    build_resource({})
    respond_with self.resource

  end



  # POST /resource
  def create
    build_resource(sign_up_params)

    resource_saved = resource.save
    yield resource if block_given?
    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  def edit
    render :edit
  end



end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/admin.html.erb
<% if login_signed_in? %>

      

<div class="row">
  <span class="pull-left"><h4>Welcome! <strong><%= current_login.company_name %></strong></h4></span>
 <a href="<%= new_invite_path %>"> <button class="btn btn-primary pull-right" data-toggle="modal" data-target=".bs-example-modal-sm">Add</button></a>
</div>
<br />




<!-- ## -->

<!-- <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Invite Friends to Join!</h4>
        </div>

          <div class="modal-body">
            <form class="form-inline" role="form">
                
                  <div class="input-group center">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                      <button class="btn btn-success" type="button">Invite!</button>
                    </span>
                  </div><!-- /input-group -->
               <!--  </form>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
    </div>
  </div>
</div> --> 




<!-- ## -->









<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Mr. <%= current_login.username %> <strong>(Admin)</strong></div>

  <!-- Table -->
  <table class="table">

      <thead>
        <tr>
          <th>Company</th>
          <th>Companyname</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
         <% @login.each do |log| %>
          <tr>
            <td><%= log.username %></td>
            <td><%= log.company_name %></td>
         
          </tr>
        <% end %>
      </tbody>


    
  </table>
</div>

<% else %>
<%=  get '/patients/:id', to: 'patients#show' %>
<% end %>




app/views/login/edit.html.erb
<%= form_for @login, url: dashboard_update_path(:id => @login.id), method: :put do |f|  %>

 
  <div class="form-group"><%= f.label :email %><br />
  <%=  @login.email %></div>
   <div class="form-group">
    <%= f.label :usertype_id %><br>
    <%= f.select :usertype_id, options_for_select([["Select One", ""], ["admin","2"],["user", "3"]]), class: "form-control" %>
  </div>
  

<div class="form-group"><%= f.submit "Update" , class: "btn btn-primary"%></div>


<% end %>

<%= link_to "Back", :back %>

app/views/login/index.html.erb
<% if login_signed_in? %>

   <div class="row">
      <span class="pull-left"><h4>Welcome! <strong><%= current_login.company_name %></strong>
       ( 
             <% if current_login.usertype_id == 1 %>
              Super Admin

                <% else 
                if current_login.usertype_id == 2 %>
                  Admin
                <% else %>
                  User
                <% end %>

            <% end %>
      ) 
</h4></span>

  <%  if @usertype == @curr_usertype || @usertype2 == @curr_usertype %>
      <a href="<%= new_invite_path %>"> <button class="btn btn-primary pull-right" data-toggle="modal" data-target=".bs-example-modal-sm">Add</button></a>
  
    <br />


<!-- Sorry! You are redirected to wrong page  -->
<% end %>

  </div>


<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Mr. <%= current_login.username %> </div>

  <!-- Table -->
  <table class="table">

      <thead>
        <tr>
          <th>Company</th>
          <th>Companyname</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
         <% @login.each do |log| %>
          <tr>
            <td><%= log.username %></td>
            <td><%= log.company_name %></td>
              <%  if @usertype == @curr_usertype %>
                  <td><%= link_to 'Show',  dashboard_show_path(:id => log.id) %></td>            
                  <td><%= link_to 'Edit', dashboard_edit_path(:id => log.id) %> </td>
                  <td><%= link_to 'Delete', dashboard_delete_path(:id => log.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
             </tr>
        <% end %>
      </tbody>


    
  </table>
</div>






<% else %>

Sorry! You are redirected to wrong page 

<% end %>

app/views/login/show.html.erb
<p id="notice"><%= notice %></p>
<% @login.each do |log| %>


<p>
  <strong>Email:</strong>
  <%= log.email %>
</p>
<p>
  <strong>First Name:</strong>
  <%= log.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= log.last_name %>
</p>
<p>
  <strong>Company Name:</strong>
  <%= log.company_name %>
</p>
<p>
  <strong>Type:</strong>
  <% if log.usertype_id == 1 %>
  Super Admin

    <% else 
    if log.usertype_id == 2 %>
      Admin
    <% else %>
      User
    <% end %>

  <% end %>
    
  
 
</p>





<%= link_to 'Back', dashboard_path %>


<% end %>


app/views/login/user.html.erb
<% if login_signed_in? %>

      

<div class="row">
  <span class="pull-left"><h4>Welcome! <strong><%= current_login.company_name %></strong></h4></span>
 <a href="<%= new_invite_path %>"> <button class="btn btn-primary pull-right" data-toggle="modal" data-target=".bs-example-modal-sm">Add</button></a>
</div>
<br />






<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Mr. <%= current_login.username %> <strong>(User)</strong></div>

  <!-- Table -->
  <table class="table">

      <thead>
        <tr>
          <th>Company</th>
          <th>Companyname</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
         <% @login.each do |log| %>
          <tr>
            <td><%= log.username %></td>
            <td><%= log.company_name %></td>
         
          </tr>
        <% end %>
      </tbody>


    
  </table>
</div>

<% else %>
<%=  get '/patients/:id', to: 'patients#show' %>
<% end %>


