config/routes.rb
Rails.application.routes.draw do

  resources :invites

  get 'dashboard' => 'login#index'
  get 'dashboard/user' => 'login#user'
  get 'dashboard/admin' => 'login#admin'
  get 'dashboard/show' => 'login#show'
  get 'dashboard/edit' => 'login#edit'
  delete 'dashboard/delete' => 'login#destroy'
  put 'dashboard/update' => 'login#update'
  get 'login' => 'login#show'

  resources :usertypes
  devise_for :logins, controllers: { registrations: "logins/registrations" }

  

  
  
  root :to => redirect("/logins/sign_in")
  

end

app/views/layouts/_footer.html.erb
<p>copyrifht 2001, rigistered!</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mingle.camp", root_url, class: "navbar-brand" %>


    </div>
     <% if login_signed_in? %>
      
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Users", dashboard_path %></li>
      <li><%= link_to "Project" %></li>
    </ul>
      
      
      <ul class="nav navbar-nav navbar-right">
       <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_login.last_name %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Edit User_Login", edit_login_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_login_session_path, :method => :delete %></li>
        </ul>
      </li>      
        
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_login_registration_path %></li>
          <li><%= link_to "Sign In", new_login_session_path %></li>
        </ul>
      <% end %>
     
      </ul>
    
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mingle.com | Basic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => "pk_test_eazzOxKLdeIQrXjACUcYAvPA" %>
  
  
</head>

<body>



<%= render 'layouts/header' %>

<div class="container">
<!--   <p class="notice alert alert-warning"><%= notice %></p>
  <p class="alert alert-success"><%= alert %></p> -->
  
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>  

    <% end %>
  <% end %>
  
  
  
<%= yield %>



<!-- <%= render 'layouts/footer' %> -->
</div>
</body>
</html>